### ISSUE TITLE
Reorigination array problem

### ISSUE THREAD

**Issue by mbabigian** [phroph/magicsim#11]
I was trying to sim a shoulder item "Mantle of Contained Corruption" which has Archive of the Titans versus Sandspinner Mantle which does not have an Uldir trait.  The former should sim higher as I have 5 stacks of the uldir buff.  MagicSim seems to be ignoring the Reorigination array buff (375 haste).  I also tried siming the Uldir piece with the SimC addon text manually edited to "stacks=0" to see if anything changed versus "stacks=5" and no difference.  

If I'm doing something wrong, let me know, but it seems bugged to me.

**Comment by phroph** [comment]
(going through old bugs)
RA not a thing anymore, might've been a SimC issue
