### ISSUE TITLE
exe file

### ISSUE THREAD

**Issue by drnym** [phroph/magicsim#2]
Thank you for your hard work in creating this program. I am excited to use it, but when I download either the zip or the Win64 and open it, there isn't a nw.exe file to click per your instructions:
'-Click nw.exe'

What am I doing wrong?  I have disabled my antivirus as was suggested to me from staff on the How To Priest Discord.

**Comment by phroph** [comment]
This is a problem with your antivirus most likely @drnym . Try temporarily suspending it or disabling it while you unzip the ZIP archive (you can turn it back on after).

**Comment by drnym** [comment]
I tried that.  I thought I had written that in the comment.  If I didn't, I apologize.  I turned off the antivirus in the control panel and I uninstalled Another antivirus that came with the computer because my subscription had lapsed and I can get it free with our cable company later.

I also restarted the computer and then went back to make sure the antivirus that is in the control panel was still off.

Thank you so much for your help.  I'd really love to try Magicsim

Michelle Allcott-Mills
Owner
American Heart Association
Training Center Coordinator 
OSHA Outreach Instructor UCSD 
General Industry and Construction 
602.418.1677 text/cell

**Comment by phroph** [comment]
You can try this direct link to the NW.exe (for x64) to see if that resolves you issue. Just copy it to where it should be

https://www.dropbox.com/s/hy3d71a7mdrqmmb/nw.exe?dl=0

**Comment by phroph** [comment]
@drnym let me know if the manually downloading the exe helps (I took that straight out of the magicsim build). So if something is deleting it you'll be immediately aware.

**Comment by drnym** [comment]
My son helped me.  I am cc him here so he can tell you why I had problems.  He's in the computer field and took control of my computer to help.  :-)

Thank you both for your assistance.

Michelle Allcott-Mills
Owner
American Heart Association
Training Center Coordinator 
OSHA Outreach Instructor UCSD 
General Industry and Construction 
602.418.1677 text/cell

**Comment by phroph** [comment]
@drnym unfortunately email responses to Github don't work that way I'm pretty sure. He can just go to this page and leave a comment or something. At least I didn't see him CC'd on the email I got, for example.

**Comment by drnym** [comment]
The issue was being caused by the file name being to large for one of the subfolders inside her windows file structure.
Current maximum path limit for windows 7 is 260 characters.

So anyways what I did was extracted the files on her c:\program files\ to drop the character path some. I would recommend less descriptive names that you as the programmer will understand. So as an example the bnode_modules could be “bnmod” and the node_modules could be “nmod” validate-npm-package-license could be simply “val-pack” changing those names alone would drop this to less than 150 characters

Ex:

C:\Users\Josh.Mills.FLOWMD\Downloads\Chrome\magicsim-1.3-patched-win64\package.nw\bnode_modules\npm\node_modules\validate-npm-package-license\node_modules\spdx-expression-parse\node_modules\spdx-exceptions\README.md

Is 216 characters I couldn’t find the file that was actually causing it in but that is pretty close to the maximum and that’s on my work downloads.

Example with changes:

C:\Users\Josh.Mills.FLOWMD\Downloads\Chrome\magicsim-1.3-X64\package.nw\bnmod\npm\nmod\valpack\nmod\spdx-exp\nmod\spdx-except\README.md

Is 135 characters

Thanks for your hard work. Have a good day.




Josh Mills
IT - Group Systems Administrator

[cid:image002.png@01D26754.0EB87890]
Flow Management Devices, LLC <http://www.flowmd.com/>
Office:  +1.602.233.9885
Cell:      +1.602.571.2093
Email:   josh.mills@flowmd.com<mailto:josh.mills@flowmd.com>




From: adoseofdharma@gmail.com [mailto:adoseofdharma@gmail.com]
Sent: Thursday, August 03, 2017 5:34 PM
To: phroph/magicsim <reply@reply.github.com>; Josh Mills <josh.mills@flowmd.com>
Cc: phroph/magicsim <magicsim@noreply.github.com>; Mention <mention@noreply.github.com>
Subject: Re: Magic Sim [phroph/magicsim] exe file (#2)

My son helped me.  I am cc him here so he can tell you why I had problems.  He's in the computer field and took control of my computer to help.  :-)

Thank you both for your assistance.
Michelle Allcott-Mills
Owner
American Heart Association
Training Center Coordinator
OSHA Outreach Instructor UCSD
General Industry and Construction
602.418.1677 text/cell

On Aug 3, 2017, at 13:15, Phillip Huff <notifications@github.com<mailto:notifications@github.com>> wrote:

@drnym<https://github.com/drnym> let me know if the manually downloading the exe helps (I took that straight out of the magicsim build). So if something is deleting it you'll be immediately aware.

**Comment by drnym** [comment]
Did you get my son's email?  If not, I'll cut and paste it.  Please let me know.

Thanks so much!

Michelle Allcott-Mills
Owner
American Heart Association
Training Center Coordinator 
OSHA Outreach Instructor UCSD 
General Industry and Construction 
602.418.1677 text/cell

**Comment by phroph** [comment]
Yes, I got the response on GitHub this time around. @drnym 

To be honest, node_modules is a pattern from Node.js. They have repeatedly said that they will _not_ allow renaming this folder because of potential ecosystem damage. It is a very problematic aspect of Node, especially with these deep folder structures (in fact, bnode_modules was originally called build_node_modules, but this was incredibly problematic).

Unfortunately these file names out of my control overall and would require a large amount sweeping restructuring.

If this is resolved I'm going to close this, and make a note to investigate better ways of dependency management. It may be possible to try something like a symlink to emulate the behavior. Not sure how node likes that, but it is worth a shot.

Please feel free to re-open or ping me if you continue to run into issues.

Sorry for the hassle!
