### ISSUE TITLE
T3 Crucible traits causing error

### ISSUE THREAD

**Issue by FredrikOedling** [phroph/magicsim#4]
When i import my Balance Druid via SimC string it leaves the first two t3 traits as 'none', if I manually assign them to their appropriate relic they sim refuses to be run ("Sims failed to be ran. Try again"). If i on the other hand leave them as 'none' the sim will run. The trait i am changing to is in both relics "Dark side of the moon".

How to reproduce:
1. From /simc
2. Pasting string (included below).
3. Change potion from unbending to prolonged power, change first and second t3 trait from "none" to "Dark Side of the Moon"
4. Add
5. Simulate. (all sim parameters are left as default)

I've tested changing the two relic slots to some other trait than the one i actually have and it seems like that will make the sim run.

PC spec:
i7-7700k
Win 10
Radeon RX 480
16gb RAM

SimC import string:
`# SimC Addon 1.9.1

druid="Kletmåne"
level=110
race=highmountaintauren
region=eu
server=shattered_hand
role=spell
professions=herbalism=794/mining=127
talents=3322132
spec=balance
artifact=59:0:0:0:0:1501:4:1502:1:1503:1:1504:25:1364:1:1294:1:1632:1:1034:4:1035:4:1036:4:1037:4:1038:4:1039:4:1040:4:1041:4:1042:4:1043:1:1044:1:1045:1:1046:1:1047:1:1048:1:1049:1
crucible=1739:1777:1036/1739:1783:1036/1739:1780:1039

head=,id=152681,bonus_id=3612/1527/3337
neck=,id=151966,enchant_id=5890,bonus_id=3611/1487/3528
shoulder=,id=152129,enchant_id=5883,bonus_id=3611/1492/3336
back=,id=151800,enchant_id=5436,bonus_id=1811/3630
chest=,id=152124,gem_id=151584,bonus_id=3611/1808/1487/3528
shirt=,id=52019
wrist=,id=137092,bonus_id=1811/3630
hands=,id=152126,bonus_id=3611/40/1487/3528
waist=,id=151991,bonus_id=3610/1507/3337
legs=,id=152128,gem_id=151584,bonus_id=3611/1808/1492/3336
feet=,id=151981,bonus_id=3611/1502/3337
finger1=,id=137532,bonus_id=3536/1612/3337
finger2=,id=133634,enchant_id=5429,bonus_id=3536/1612/3337
trinket1=,id=137419,bonus_id=3418/1602/3337
trinket2=,id=151955,bonus_id=3611/1487/3528
main_hand=,id=128858,gem_id=155846/142309/144463,bonus_id=722,relic_id=3611:1497:3528/3536:1572:3337/3536:1592:3528

### Gear from Bags
#
.
.
.
`

**Comment by phroph** [comment]
Looks like a bug with crucible parsing. In my data I have 'Dark Side of the Moon' marked with ID 1281 where your crucible it seems to be ID 1036. I should fix this in the next day or so.

(Should note, unfortunately no way to workaround this until I fix this. You'll have to omit crucible for the time being)

**Comment by phroph** [comment]
Marking this as closed @kletmane . Feel free to reopen if problem persists in the new version.
